#!/bin/bash
echo "welcome to penyashar"
##programmer: yashar esmaildokht|+989141100257
##email : royaflash@gmail.com
##website: http://unixmen.ir
##

case "$1" in
        start)
            start
            ;;
         
        stop)
           killall penyashar
            ;;
         
        status)
            tob -b -n 1 |grep -i "penyashar"
            ;;
       
              
        *)
            echo $"Usage: $0 {start|stop|status}"
            exit 1
 
esac





echo "---------menue------------------"
		echo "                                     .::!!!!!!!:. "
		echo "  .!!!!!:.                        .:!!!!!!!!!!!! "
		echo "  ~~~~!!!!!!.                 .:!!!!!!!!!UWWW$$$ "
		echo "      :$$NWX!!:           .:!!!!!!XUWW$$$$$$$$$P "
		echo "      $$$$$##WX!:      .<!!!!UW$$$$   $$$$$$$$# "
		echo "      $$$$$  $$$UX   :!!UW$$$$$$$$$   4$$$$$* "    
		echo "      ^$$$B  $$$$      $$$$$$$$$$$$   d$$R* "
		echo "        **$bd$$$$      '*$$$$$$$$$$$o+#  "
		echo "             ****          ******* " 
echo "-->"
 echo "1)Network tools"
 echo "2)baner grabbing"
 echo "3)web"
 echo "4)recovery tools"
 echo "5)Wireless tools"
 echo "6)cryptography"
 echo "f)fun tools"
 echo "r)repository tools"
 echo "d)programmer demo"
 echo "u)update penyashar"


  echo "v)version and programmer info "
read NOW
 case $NOW in 
0)
  ./test 
 ;;
  1) 

 	echo "1-1)your ip"
        echo "1-2) internet ip"
        echo "1-3) check your listner port"
        echo "1-4) check your network conections" 	
        echo "1-5) honeypot"
        echo "1-6) network uuid"
        echo "1-7) 10baseip"
	echo "1-8)MAC address geolocation"
        echo "1-9)ddos"
        echo "1-10)Secure tunnels to localhost"
 ;;

   2)

echo "2-1) theHarvester (Information Gathering suite)"
         ;; 	


 3)
 
 echo "3-1)golismero"
;;
v)
    echo "version 0.1"
    echo "programmer yashar esmaildokht |http://unixmen.ir"
;; 

5)
 echo "5-1)show saved wifi password"
;;

 6)
    echo "6-1)Hash Password Cracker (MD5, SHA1, SHA256, SHA384, SHA512, RIPEMD-160)"
    echo "6-2)Base64 Encoder & Decoder"
    echo "6-3)Secure Password Generator"
    echo "6-4)Multi-Digest (MD5, SHA1, SHA256, SHA384, SHA512, RIPEMD-160)"
;;
*)

 echo "invalid key"
;; 

esac 

 read num 
  case $num in 
   1-1)
              ip a
 ;;
 
     1-2)
              curl ifconfig.me
               echo "0)back"
read
    ;;   
1-3)
               netstat -l |less 
               echo "0)back"
read
    ;;   
1-4)
               lsof -i |less 
               echo "0)back"
read
    ;;   
1-5)
 cd .tools/
 ./honeypot.rb
    ;;   
 1-7)

 ./.tools/10base
;;
1-8)

 ./.tools/mac.rb
;;
   
1-9)
echo "1-9-1)hulk"
echo "1-9-2)goldeneye"
read dos
;;
2-1)
cd .tools/
 ./the
               echo "0)back"
cd .tools/
    ;;   

3-1)
 python .tools/golismeroo.py

;;

5-1)
./.tools/wifre
;;
6-1) 
  ./.tools/hash.rb
;;
6-2) 
  ./.tools/base64.rb
;;
6-3) 
  ./.tools/secure.rb
;;
6-4) 
  ./.tools/multi.rb
;;
esac
case $dos in 
 1-9-1)
 echo "please enter url for example: http://example.com"
 echo "you can add '"safe"' after url, to autoshut after dos"
 read hulk 
 python .tools/hulk.py $hulk

;;

1-9-2)

 echo " USAGE: <url> [OPTIONS] "
    
echo -e "OPTIONS:"
echo -e "Flag           Description                     Default "
echo -e "-u, --useragents   File with user-agents to use                     (default: randomly generated)"
echo -e "-w, --workers      Number of concurrent workers                     (default: 50)"
echo "   -s, --sockets      Number of concurrent sockets                     (default: 30)"
echo "   -m, --method       HTTP Method to use 'get' or 'post'  or 'random'  (default: get)"
echo "   -d, --debug        Enable Debug Mode [more verbose output]          (default: False)"
echo "   -h, --help         Shows this help"
echo -e " example : http://example.com -d "
 read golden 
 python .tools/geye.py $golden


;;


esac






